### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/clone-tabnews#9]
- [x] Estabilizar Ambiente Local
- [x] Estabilizar Testes Locais
- [x] Estabilizar o CI
- [x] Refatorações Gerais

**Comment by samdamazio** [comment]
![5ykse1](https://github.com/filipedeschamps/clone-tabnews/assets/128763505/30b47ad8-cdf0-464b-ba40-b4ad3c32643d)

**Comment by Rosicre** [comment]
Aqui é onde a Vaca Chora e a Mãe não Ver. 
![images](https://github.com/filipedeschamps/clone-tabnews/assets/94906196/e4c0aa45-82de-43aa-a654-2e459301c9c6)

**Comment by Rosicre** [comment]
Evolução e Manutenção é um dos gargalos da nossa área, existem equipes que fazem commits apenas 1 vez ao mês, parece brincadeira más é verdade, olha só a quantidade de códigos inconsistentes que serão necessário avaliar! Por isso Integração contínua, realizar commit pelo menos 1 vez por dia para dar mais qualidade e velocidade.

![evolucao](https://github.com/filipedeschamps/clone-tabnews/assets/94906196/9176a7e9-310e-4aa9-af0c-ac8e72664236)

**Comment by RenanMatias** [comment]
Fundação has completed!!!
